### PR TITLE
[FEATURE] Add count behind percentage to have a better visualisation

### PR DESCRIPTION
**Pull request by tomasnorre**
I would like to suggest that the report information is not only displayed in percentage, but also with the real number. 

We are doing some monitoring on this for our projects, so perhaps even separate the two information, so they are easier to grep would help us too. 

But first I would like your feedback.

### CODE REVIEW

**Comment by tomasnorre** [comment]
This is how it looks for html and markdown, with my simple suggestion. 

typo3scan-report-html
typo3scan-report-markdown

**Comment by tomasnorre** [comment]
That was fast... Thanks.

**Comment by Tuurlijk** [comment]
Thank you sir! ;-)

**Comment by Tuurlijk** [comment]
Release 1.6.2 is here

**Comment by tomasnorre** [comment]
Wish I was that fast with the repositories i was maintaining.. Thanks a lot.

**Pull request merged**
